package com.revature.util;

public class ERSConstants {
	
	public static final String EMPLOYEE_MESSAGE_REGISTRATION_SUCCESSFUL = "REGISTRATION SUCCESSFUL";
	public static final String EMPLOYEE_MESSAGE_REGISTRATION_UNSUCCESSFUL = "REGISTRATION UNSUCCESSFUL";
	public static final String EMPLOYEE_MESSAGE_UPDATE_SUCCESSFUL = "UPDATE SUCCESSFUL";
	public static final String EMPLOYEE_MESSAGE_UPDATE_FAILED = "UPDATE FAILED";
	public static final String EMPLOYEE_MESSAGE_VIEW_INFORMATIOAN = "REQUEST VIEW INFORMATION UNSUCCESSFUL";
	public static final String EMPLOYEE_MESSAGE_UNKNOWN_FOR_NOW= "REGISTRATION SUCCESSFUL";
	public static final String EMPLOYEE_MESSAGE_VIEW_EMP_LIST = "REQUEST VIEW ALL UNSUCCESSFUL";
	public static final String EMPLOYEE_MESSAGE_USERNAME_AVAILABLITY_VALID = "VALID USERNAME";
	public static final String EMPLOYEE_MESSAGE_USERNAME_AVAILABLITY_UNSUCCESSFUL = "USERNAME EXISTS";
	public static final String EMPLOYEE_MESSAGE_USERNAME_TAKEN = "USERNAME EXIST";
	
	
	public static final String REIMBURSEMENT_SUBMIT_UNSUCCESSFUL = "FAILED TO SUBMIT REQUEST";
	public static final String REIMBURSEMENT_SINGLE_REQUEST_UNSUCCESSFUL = "REQUEST UNSUCCESSFUL";
	public static final String REIMBURSEMENT_MULTI_REQUEST_UNSUCCESSFUL = "MULTI-RQUEST UNSUCCESSFUL";
	public static final String REIMBURSEMENT_EMP_NOLIST = "NO REIMBURSEMENT TO DISPALY";
	public static final String REIMBURSEMENT_MNGR_NOLIST="NO REIMBURSEMENT TO DISPALY";
	public static final String REIMBURSEMENT_FINAL_REQUEST_UNSUCCESSFUL= "RESOLVED REQUEST UNSUCCESSFUL";
	public static final String REIMBURSEMENT_REQUEST_TYPE_MESSAGE = "INTERNAL ERROR";
	
	public static final String SUCCESS_MESSAGE ="TRANSACTION SUCCESSFUL";
	public static final String UNAUTHORIZED_ATTEMPT_MESSAGE = "UNAUOTHORIZED ACCESS";
	
	
	
	
	
	

}
